# this Makefile needs cargo-make, see https://github.com/sagiegurari/cargo-make

[config]
# Skip loading of all core tasks which saves up a bit on toml parsing and task creation
skip_core_tasks = true
# Skips loading Git related environment variables
skip_git_env_info = true
# Skips loading rust related environment variables
skip_rust_env_info = false
# Skips loading the current crate related environment variables
skip_crate_env_info = true


[env]
CARGO_VERSION = { script = ["cargo pkgid | cut -d '@' -f2"] }


# Linting and testing tasks
[tasks.lint]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.test]
command = "cargo"
args = ["test"]

# Cross-compilation task for building on Linux
[tasks.build-linux]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-unknown-linux-gnu"]

[tasks.build-linux-debug]
command = "cargo"
args = ["build", "--target", "x86_64-unknown-linux-gnu"]

# Cross-compilation task for building on Windows
[tasks.build-windows]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-pc-windows-gnu"]

[tasks.build-windows-debug]
command = "cargo"
args = ["build", "--target", "x86_64-pc-windows-gnu"]

# Cross-compile for both platforms
[tasks.build-all]
dependencies = ["build-linux", "build-windows"]

[tasks.build-all-debug]
dependencies = ["build-linux-debug", "build-windows-debug"]

# Copy artifacts to a dist folder
[tasks.deploy-linux]
dependencies = ["build-linux"]
script = [
    "mkdir -p dist/linux",
    "cp target/x86_64-unknown-linux-gnu/release/tracker dist/linux/tracker.bin",
]

[tasks.deploy-windows]
dependencies = ["build-windows"]
script = [
    "mkdir -p dist/windows",
    "cp target/x86_64-pc-windows-gnu/release/tracker.exe dist/windows/tracker.exe",
]

[tasks.deploy]
dependencies = ["build-all", "deploy-linux", "deploy-windows"]

# Package Linux binary into platform-specific zip
[tasks.package-linux]
dependencies = ["deploy-linux"]
script = [
    "mkdir -p dist/linux",
    "cd dist/linux && zip -r ../time-tracker-cli-${CARGO_VERSION}-x86_64-linux.zip tracker.bin",
    "rm -rf ../linux",
]

# Package Windows binary into platform-specific zip
[tasks.package-windows]
dependencies = ["deploy-windows"]
script = [
    "mkdir -p dist/windows",
    "cd dist/windows && zip -r ../time-tracker-cli-${CARGO_VERSION}-x86_64-windows.zip tracker.exe",
    "rm -rf ../windows",
]

# Package all platforms
[tasks.package]
dependencies = ["package-linux", "package-windows"]

[tasks.cleanup]
script = [
    """
    cargo clean
    rm -r dist/
    """,
]

[tasks.setup]
command = "rustup"
args = ["target", "add", "x86_64-pc-windows-gnu"]
