# this Makefile needs cargo-make, see https://github.com/sagiegurari/cargo-make

[config]
# Skip loading of all core tasks which saves up a bit on toml parsing and task creation
skip_core_tasks = true
# Skips loading Git related environment variables
skip_git_env_info = true
# Skips loading rust related environment variables
skip_rust_env_info = false
# Skips loading the current crate related environment variables
skip_crate_env_info = true


[env]
CARGO_VERSION = { script = ["cargo pkgid | cut -d '@' -f2"] }


# Cross-compilation task for building on Linux
[tasks.build-linux]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-unknown-linux-gnu"]

[tasks.build-linux-debug]
command = "cargo"
args = ["build", "--target", "x86_64-unknown-linux-gnu"]

# Cross-compilation task for building on Windows
[tasks.build-windows]
command = "cargo"
args = ["build", "--release", "--target", "x86_64-pc-windows-gnu"]

[tasks.build-windows-debug]
command = "cargo"
args = ["build", "--target", "x86_64-pc-windows-gnu"]

# Cross-compile for both platforms
[tasks.build-all]
dependencies = ["build-linux", "build-windows"]

[tasks.build-all-debug]
dependencies = ["build-linux-debug", "build-windows-debug"]

# Copy artifacts to a dist folder
[tasks.deploy-linux]
dependencies = ["build-linux"]
script = [
    "mkdir -p dist",
    "cp target/x86_64-unknown-linux-gnu/release/tracker dist/tracker-${CARGO_VERSION}.bin",
]

[tasks.deploy-windows]
dependencies = ["build-windows"]
script = [
    "mkdir -p dist",
    "cp target/x86_64-pc-windows-gnu/release/tracker.exe dist/tracker-${CARGO_VERSION}.exe",
]

[tasks.deploy]
dependencies = ["build-all", "deploy-linux", "deploy-windows"]

[tasks.package]
dependencies = ["deploy"]
script = [
    "zip -r dist/time-tracker-cli-${CARGO_VERSION}.zip dist/",
]

[tasks.cleanup]
script = [
    """
    cargo clean
    rm -r dist/
    """,
]