name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust environment
        uses: ./.github/actions/setup-rust-env
        with:
          cache-key-suffix: '-release'
          install-mingw: 'true'

      - name: Build and package all platforms
        run: cargo make package

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip